# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtei', '0003_rteidocument_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rteidocument',
            name='file',
            field=models.FileField(blank=True, help_text='Use this to upload a file and list it as a resource', null=True, upload_to='documents', verbose_name='file'),
        ),
    ]
