# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtei', '0005_auto_20190928_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Determines whether document appears in the Featured Contents.'),
        ),
    ]
