# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 16:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wagtail.wagtailsearch.index
import wagtail.wagtailcore.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0028_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtei', '0006_resource_model_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='RteiDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('year', models.CharField(help_text='e.g. 1999', max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 4 numbers', regex='^\\d{4}$')])),
                ('country', models.CharField(max_length=256)),
                ('is_resource', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(default=wagtail.wagtailcore.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'document',
            },
            bases=(models.Model, wagtail.wagtailsearch.index.Indexed),
        ),
        migrations.RemoveField(
            model_name='resourcedocument',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='resourcedocument',
            name='page',
        ),
        migrations.DeleteModel(
            name='ResourceDocument',
        ),
    ]
