# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 10:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rtei', '0007_auto_20160405_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='rteidocument',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rteidocument',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='rteidocument',
            name='is_resource',
            field=models.BooleanField(default=True, help_text='Determines whether document appears on the Resources page.'),
        ),
        migrations.AlterField(
            model_name='rteidocument',
            name='year',
            field=models.CharField(blank=True, help_text='e.g. 1999', max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 4 numbers', regex='^\\d{4}$')]),
        ),
    ]
