# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtei', '0010_rteiancillarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='order_in_menu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceindexpage',
            name='order_in_menu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rteiancillarypage',
            name='order_in_menu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rteipage',
            name='order_in_menu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
