# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 10:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtei', '0011_auto_20170322_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='rteidocument',
            name='external_url',
            field=models.TextField(blank=True, help_text='Use this to add an external website as a listed resource', validators=[django.core.validators.URLValidator]),
        ),
    ]
