# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:05
from __future__ import unicode_literals

from django.db import migrations


def load_stores_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "0002_initial_data")


class Migration(migrations.Migration):
    pass
    # dependencies = [
    #     ('rtei', '0001_initial'),
    # ]

    # operations = [
    #     migrations.RunPython(load_stores_from_fixture),
    # ]
